# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FoodSuggestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import handle.main as handle

class Ui_FoodSuggestion(object):
    def setupUi(self, FoodSuggestion):
        self.NFOF = handle.NFOF()
        self.find_result = None
        self.select_result = None
        self.seach_google = None
        FoodSuggestion.setObjectName("FoodSuggestion")
        FoodSuggestion.resize(800, 600)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(FoodSuggestion)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(FoodSuggestion)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("font: 24pt \"Arial\";")
        self.label.setLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(FoodSuggestion)
        self.frame.setEnabled(True)
        self.frame.setStatusTip("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtSearch = QtWidgets.QLineEdit(self.groupBox)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(self.groupBox)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbSearchForm = QtWidgets.QGroupBox(self.frame_2)
        self.gbSearchForm.setObjectName("gbSearchForm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbSearchForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lvSearch = QtWidgets.QListView(self.gbSearchForm)
        self.lvSearch.setObjectName("lvSearch")
        self.verticalLayout_2.addWidget(self.lvSearch)
        self.btnSuggestion = QtWidgets.QPushButton(self.gbSearchForm)
        self.btnSuggestion.setObjectName("btnSuggestion")
        self.verticalLayout_2.addWidget(self.btnSuggestion)
        self.horizontalLayout_2.addWidget(self.gbSearchForm)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lvResult = QtWidgets.QListView(self.groupBox_3)
        self.lvResult.setObjectName("lvResult")
        self.verticalLayout_3.addWidget(self.lvResult)
        self.btnGoogleSearch = QtWidgets.QPushButton(self.groupBox_3)
        self.btnGoogleSearch.setObjectName("btnGoogleSearch")
        self.verticalLayout_3.addWidget(self.btnGoogleSearch)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(FoodSuggestion)
        QtCore.QMetaObject.connectSlotsByName(FoodSuggestion)
        
        self.btnSuggestion.setEnabled(False)
        self.btnGoogleSearch.setEnabled(False)
        self.btnClear.setEnabled(False)
        
        self.modelSearchList = QtGui.QStandardItemModel()
        self.modelSuggestionList = QtGui.QStandardItemModel()
        self.lvSearch.setModel(self.modelSearchList)
        self.lvResult.setModel(self.modelSuggestionList)
        
        self.btnClear.clicked.connect(self.ClearFood)
        self.btnSuggestion.clicked.connect(self.suggestionFood)
        self.btnSearch.clicked.connect(self.searchFood)
        self.btnGoogleSearch.clicked.connect(self.SeachGoogle)
        self.lvSearch.selectionModel().currentChanged.connect(self.selectSearchList)
        self.lvResult.selectionModel().currentChanged.connect(self.selectSuggestionList)
        
        

    def retranslateUi(self, FoodSuggestion):
        _translate = QtCore.QCoreApplication.translate
        FoodSuggestion.setWindowTitle(_translate("FoodSuggestion", "Food Suggestion Software"))
        self.label.setText(_translate("FoodSuggestion", "Food Suggestion Software"))
        self.groupBox.setTitle(_translate("FoodSuggestion", "Input"))
        self.btnSearch.setText(_translate("FoodSuggestion", "Search"))
        self.btnClear.setText(_translate("FoodSuggestion", "Clear"))
        self.gbSearchForm.setTitle(_translate("FoodSuggestion", "Search Result"))
        self.btnSuggestion.setText(_translate("FoodSuggestion", "Suggestion"))
        self.groupBox_3.setTitle(_translate("FoodSuggestion", "Suggestion Result"))
        self.btnGoogleSearch.setText(_translate("FoodSuggestion", "Google Search"))

    def searchFood(self):
        self.modelSuggestionList.removeRows( 0, self.modelSuggestionList.rowCount() )
        self.modelSearchList.removeRows( 0, self.modelSearchList.rowCount() )
        self.btnSuggestion.setEnabled(False)
        self.btnGoogleSearch.setEnabled(False)
        self.btnClear.setEnabled(True)
        self.select_result = None
        self.seach_google = None
        product_name = self.txtSearch.text().strip()
        self.find_result = self.NFOF.find(product_name)
        for i in self.find_result:
            item = QtGui.QStandardItem(i['name'])
            self.modelSearchList.appendRow(item)
            
    def selectSearchList(self, current, previous):
        self.select_result = self.find_result[current.row()]
        self.btnSuggestion.setEnabled(True)
        
    def selectSuggestionList(self, current, previous):
        self.seach_google = current.data()
        self.btnGoogleSearch.setEnabled(True)

    def suggestionFood(self):
        self.modelSuggestionList.removeRows( 0, self.modelSuggestionList.rowCount() )
        self.btnGoogleSearch.setEnabled(False)
        self.seach_google = None
        self.NFOF.set_food(self.select_result['name'])
        listFood = self.NFOF.predict()
        for i in listFood:
            item = QtGui.QStandardItem(i)
            self.modelSuggestionList.appendRow(item)
    
    def SeachGoogle(self):
        url = QtCore.QUrl('https://www.google.com/search?q='+self.seach_google)
        QtGui.QDesktopServices.openUrl(url)
                
    
    def ClearFood(self):
        self.txtSearch.setText("")
        self.select_result = None
        self.seach_google = None
        self.modelSearchList.removeRows( 0, self.modelSearchList.rowCount() )
        self.modelSuggestionList.removeRows( 0, self.modelSuggestionList.rowCount() )
        self.btnSuggestion.setEnabled(False)
        self.btnGoogleSearch.setEnabled(False)
        self.btnClear.setEnabled(False)
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_FoodSuggestion()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())